---
title: "第五章 智能交易的云计算平台：以DigitalOcean为例 "
author: "Qiufei"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

## 计算能力是我们实现分析的基础 ##

* 我们的操作流程是：数据 -- 分析 -- 策略 -- 交易

* 数据--分析 -- 策略，这三部都需要有计算能力或者说电脑的支撑

* 到目前为止，我们的操作都是在本地电脑（也就是我们自己的电脑上）完成的

## 只用自己的电脑的问题 ##

1. 我的电脑不光是为了运行R语言程序用的，万一程序有冲突怎么办？

2. 我的电脑不可能一天24小时开始，而如果我的设计的算法策略要求电脑不断网随时待命怎么办？

3. 虽然我们的电脑很轻，但是我也没法随时带着它，电脑不在手边的时侯，我需要进行分析操作怎么办？

4. 我想下载海量数据进行大数据分析，但是家里的网络速度太慢怎么办？

5. 我的算法对电脑的配置要求比较高，比如需要32核的处理器，224G的内存，这种配置的电脑市面上都没有卖的，怎么办？

## 云计算平台提供了可伸缩的计算能力 ##

1. 云计算平台首先是提供了一个在线的服务器，只要有浏览器连着网，你可以随时登陆你的服务器进行操作。

2. 云服务平台维护你的服务器，可以做到一天24小时开机运行，且平台的网速超快，不用担心网络的制约问题。

3. 云平台可以方便的调整你的计算能力，当你只是验证想法阶段，你可以选择较低配置的计算能力，比如只需要1核处理器，1G的内存。当你要开始真正干活的时侯，你可以选择高配置计算能力，比如32核处理器，224G内存。

4. 云计算平台一般可以按小时收费，这样可以大大节省费用。


## 云计算平台种类 ##



1. digitalocean是美国的一家云计算平台公司

2. 其他著名的云计算平台还有微软的azure，亚马逊的aws，IBM的Bluemix

他们的共同特点是贵。

3. 国内也有其他的云计算平台，比如阿里云，百度云。

他们的特点是也很贵，而且还很麻烦。


## 为什么选择DigitalOcean平台 ##

1. 价格：都以1核1GB的配置来看
- 阿里云一个月费用是93元人民币。
- 百度云一个月费用是45元人民币。
- digitalocean一个月费用是5美元，不到35元人民币。

## 为什么选择DigitalOcean平台 ##

2. 学习与服务

- digitalocean有完善的教程，基本上你想在云平台上实现的事情，都会有详细的帖子教你怎么操作。起步早的云平台比如亚马逊的aws也有这个优点。

- 国内云平台似乎都是给专家用的，很少有教程文档存在。


## 在DigitalOcean上部署自己的云端R服务器 ##

* digitalocean 在创建实例的时侯，有个用户设置区，在该区域内写入如下代码：

`#cloud-config`

`runcmd:`

`  - docker pull rocker/hadleyverse`

`  - docker run -d -p 8787:8787 rocker/hadleyverse`

安装完毕后，登陆你的服务器，用户名和密码都为rstudio

## 在自己的服务器上定时更新分析报告 ##

* 假设以下你个场景，毕业后你成为某个基金的操盘手，需要实时关注
