---
title: "函数"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 复利

$$ a(t) = (1+r)^t $$

```{r}
fl = function(r,t){
  at = (1+r)^t
  return(at)
}

fl(0.05,10)
```

## 贴现

$$ p(t) = (1+r)^{-t} $$

```{r}
tx = function(r,t){
  at = (1+r)^(-t)
  return(at)
}

tx(0.05,10)

```

## 复利终值

$$ fv = a(1+r)^t $$

```{r}
fv = function(a,r,t){
  v = a*(1+r)^t
  return(v)
}

fv(1000,0.08,10)
```


## 复利现值

$$ fv = a(1+r)^{-t} $$

```{r}
pv = function(a,r,t){
  v = a*(1+r)^(-t)
  return(v)
}

pv(3000,0.08,5)
```




## 付息债券

$$  P = \sum_{t=1}^{N} \frac{C_t}{(1+y)^t} + \frac{face}{(1+y)^N} $$

```{r}
bond_pv = function(ct,face,y,n){
  t = 1:n
  c = ct/(1+y)^t
  b = face/(1+y)^n
  bond = sum(c) + b
  return(bond)
}

```

## 债券计算

- 新发行的三年期债券面值1000元，每半年付息50元，市场利率为12%，请问债券现值为多少？

```{r}
bond_pv(50, 1000, 0.06, 6)
```


## 敏感度分析：久期分析 ##

久期（duration）就是加权到期时间。

一般计算公式如下：


$$ D = \frac{PV_{t_0}t_0+PV_{t_1}t_1+PV_{t_2}t_2+...+PV_{t_n}t_n}{PV}$$
 

其中
 
$$ PV = PV_{t_0}+PV_{t_1}+PV_{t_2}+...+PV_{t_n} $$

* 这个是久期计算的一般公式，一般在于它没有说明用何种利率来折现。

## macaulay久期

* 如果用债券的收益率来折现，那么计算得到的就是macaulay久期。

* 金融工具一年内支付m次，在每期支付的金额为$c_i$，还需要支付n次，$y$为到期收益率,那么这项金融工具的macaulay久期计算公式为：

$$ D = \sum_{i}^{n}\frac{i}{m}\frac{c_i}{[1+(\frac{y}{m})]^i}\frac{1}{PV}   $$

$$ PV = \sum_{i}^{n}\frac{c_i}{[1+(\frac{y}{m})]^i} $$



## 久期计算函数

```{r}

duration = function(ci,face,y,n,m){
  i = 1:n
  c = ci/(1+y/m)^i
  b = face/(1+y/m)^n
  pv = sum(c) + b

  time_ct = (i/m)*ci/(1+y/m)^i
  time_face = (n/m)*face/(1+y/m)^n
  time = sum(time_ct) + time_face
  dur = time/pv
  return(dur)
  }

```



##  例子：计算久期
- 债券收益率8%，票面利率7%，还有三年到期，每半年支付一次利息，请计算久期。

```{r}

duration(3.5,100,0.08,6,2)
```








